### ISSUE TITLE
Avoid language extensions

### ISSUE THREAD

**Issue by tfausak** [EdutainmentLIVE/haskell-style-guide#13]
``` hs
-- bad
{-# LANGUAGE LambdaCase #-}
\case
  () -> ()

-- good
\ x -> case x of
  () -> ()
```

In general we try to avoid using language extensions because they're just another thing to explain. Sometimes they are harmless like `TypeSynonymInstances`. Some can't be avoided like `EmptyDataDecls`. Others are pure syntactic sugar like `OverloadedStrings`. Others are just a bad idea like `IncoherentInstances`. 

We should come up with a concrete list of allowed language extensions. I imagine a few categories:

- Always enabled (`default-extensions`)
- Permitted and encouraged if necessary (via `LANGUAGE` pragmas)
- Begrudgingly allowed in some circumstances
- Downright forbidden

**Comment by tfausak** [comment]
This post has an excellent overview of a large swath of the available language extensions: https://lexi-lambda.github.io/blog/2018/02/10/an-opinionated-guide-to-haskell-in-2018/#any-flavor-you-like

**Comment by qxjit** [comment]
+1000.
