### ISSUE TITLE
Use type wrappers liberally

### ISSUE THREAD

**Issue by tfausak** [EdutainmentLIVE/haskell-style-guide#18]
``` hs
-- bad
type Email = Text

-- good
module Email ( Email, toEmail, fromEmail ) where
newtype Email = Email Text
toEmail x = if isEmail x then Just (Email x) else Nothing
fromEmail (Email x) = x
```

Type aliases (with `type`) don't add any type safety. Prefer type wrappers (with `newtype`) instead. Hide the constructor and provide functions for wrapping and unwrapping the type. Don't use record fields (`newtype T = C { f :: () }`) because they can break the entire point of your type wrapper.

**Comment by telser** [comment]
:+1: I think we should make sure to stress the last point in the style guide, however that ends up being written.

**Comment by tfausak** [comment]
I'll be sure to include a (shameless) link to http://taylor.fausak.me/2018/03/16/record-fields-break-smart-constructors/

**Comment by qxjit** [comment]
:+1:
