### ISSUE TITLE
Use camel case names

### ISSUE THREAD

**Issue by tfausak** [EdutainmentLIVE/haskell-style-guide#19]
``` hs
-- bad
type SCREAMING_SNAKE_CASE = ()
type Camel_Snake_Case = ()
snake_case = ()

-- good
type PascalCase = ()
camelCase = ()
```

This should be pretty straightforward. The whole community does this.

One thing we need to decide on is how to capitalize all-caps stuff like "IO", "ID", and "XML HTTP Request".

``` hs
type IO = () -- good
type SomeID = () -- kind of weird
type XMLHTTPRequest = () -- awkward

type Io = () -- awkward
type SomeId = () -- good
type XmlHttpRequest = () -- good
```

I prefer `XmlHttp` to `XMLHTTP`. In general I like thinking about how something would be written in `kebab-case` and then converting it into `KebabCase` by capitalizing each work and removing the hyphens. It kind of falls apart with `IO`, which would be written as `io` in kebab-case, which would be converted into `Io`, which looks weird. That's pretty much the only exception for me though.

**Comment by telser** [comment]
At some point we said "acronyms should be all-caps" which gives `IO`, `SomeId`, and `XMLHTTPRequest`. It is a compromise, but it does make things easy to follow/reason about and doesn't have any exceptions to my knowledge. :man_shrugging: 

On a more humorous note, reading `Io` makes me thing of the [programming language](https://en.wikipedia.org/wiki/Io_(programming_language))

**Comment by qxjit** [comment]
Absolutely, with the caveat there I do think there is a 0.1% case where you really do need a prefix that deserves to be separated with an underscore. I don't have an example off hand, but I know I've hit it a couple of times over the past two years. I always try to avoid exposing it to outside users -- usually it's to make the internal code of a module more readable.

**Comment by tfausak** [comment]
I agree that underscores are sometimes necessary, but I also can't think of any examples off the top of my head 😆 

One thing I've seen pop up in other style guides is to only capitalize two-letter acronyms. Everything else only gets the initial cap. For example: `IO` is all caps, but `Xml` only has the initial cap. I like that, with the exception that I prefer `Id` to `ID`. What do y'all think?

**Comment by tfausak** [comment]
I've started to consider using underscores for field prefixes. For example:

``` hs
data Person = Person
  { person_name :: Text
  , person_age :: Natural }
```

That way the field, like `person_name`, doesn't collide with some value that happens to represent the person's name. I frequently run into situations where, with a field called `personName`, I'll end up with a value called `pName` or `personName_` or something like that. 

On the other hand, records are normally tucked away in a separate module and usually imported qualified, so this doesn't come up that much. Probably not worthwhile.
