### ISSUE TITLE
Avoid back tick operators

### ISSUE THREAD

**Issue by tfausak** [EdutainmentLIVE/haskell-style-guide#24]
``` hs
-- bad
apple `elem` fruits

-- good
elem apple fruits
```

Turning a regular function into an infix "operator" using back ticks is pretty weird and each to miss. We should prefer calling functions the normal way. We could make an exception for Hspec's `shouldBe` and friends. 

Similarly, we should avoid turning operators into normal functions.

``` hs
-- bad
(+) 1 2

-- good
1 + 2
```

The only time that's acceptable is when you're passing an operator to something like `foldr (+) 0 xs`.

**Comment by telser** [comment]
I can think of one other time it _might_ be acceptable. Creating a named alias for an operator that doesn't have one, so you can avoid using the operator version   :)

**Comment by tfausak** [comment]
Oh yeah good call! `plus = (+)` is way nicer than `plus x y = x + y`.

As for infix functions, one notable exception will be ``actual `shouldBe` expected`` in tests.

**Comment by tfausak** [comment]
One particularly tricky aspect of infix functions is that they too can have custom fixities: https://np.reddit.com/r/haskelltil/comments/2zkz8w/functions_not_just_operators_can_have_fixity_and/

I have trained myself to not mind `elem x xs`, but I agree that ``x `elem` xs`` reads better. It's not clear to me what "deserves" to be used infix. For example, I normally call `Data.Text.isPrefixOf` as a normal function even though it reads better as infix. That might be because qualified infix functions are almost as ugly as qualified operators.

``` hs
Text.isPrefixOf "ax" "axle"
"ax" `Text.isPrefixOf` "axle"
```

**Comment by gera-cameron** [comment]
We use them for tests and I think it works well!

**Comment by aschmois** [comment]
I think the tests are an exception to the rule. I still think we should avoice backtick wherever possible throughout codebases.

**Comment by tfausak** [comment]
Should we define custom operators for setting expectations in tests? For example HUnit has [`(~?=)`](https://hackage.haskell.org/package/HUnit-1.6.2.0/docs/Test-HUnit-Base.html#v:-126--63--61-), among others. We could do say something like:

``` hs
(==?) = shouldBe
```
