### ISSUE TITLE
Avoid guard clauses

### ISSUE THREAD

**Issue by tfausak** [EdutainmentLIVE/haskell-style-guide#25]
``` hs
-- bad
f x
  | x > 0 = x * 2
  | x < 0 = x / 2
  | otherwise = x

-- good
f x =
  if x > 0 then x * 2
  else if x < 0 then x / 2
  else x
```

Guard clauses don't come up all that often in application code, but prefer using regular conditionals instead of them anyway.

**Comment by codygman** [comment]
I feel the guard clause above is far more readable and feel a tad more strongly than @qxjit about it. I see that given #43 was opened recently we are open to using guards in some places.

**Comment by tfausak** [comment]
Yeah my opinion has softened a little bit. I'm alright with guards, although I still don't like how they play with variable scoping (especially combined with `where`). Maybe this suggestion could be even more specific, like: Prefer conditionals over single guards? In other words, `f x | p x = y | otherwise = z` is hokey, and `f x = if p x then y else z` is preferred.

**Comment by qxjit** [comment]
In support of @codygman I'll at least volunteer that I would feel more strongly in favor of guards if this were the Flipstone style guide rather than the EdutainmentLIVE style guide 😉

**Comment by tfausak** [comment]
Closing this one. I don't feel strongly one way or the other about guard clauses.

**Comment by aschmois** [comment]
I also think guard clauses are one of the first things taught in haskell and maybe we should begin to lean into them a little more. It definitely makes the code more uniform in the simple cases but they shouldn't be a complete replacement to all logic checks.
