### ISSUE TITLE
Prefer separate lets

### ISSUE THREAD

**Issue by tfausak** [EdutainmentLIVE/haskell-style-guide#26]
``` hs
-- bad
do
  let
    x = 2
    y = 3
  pure (x * y)

-- good
do
  let x = 2
  let y = 3
  pure (x * y)
```

I have a slight preference for multiple `let`s over a single `let` with multiple binders. We should pick one and go with it.

**Comment by tfausak** [comment]
I slightly prefer multiple `let`s because they prevent you from making mutually recursive declarations, which is almost never what you want.

``` hs
-- compiles
let
  f x = g x
  g x = f x

-- doesn't compile
let f x = g x
let g x = f x
```

I feel that any mutually recursive functions should be lifted to the top level.

**Comment by telser** [comment]
I like the point about mutually recursive functions, but prefer a single let personally. That does mean you rely on a different convention for the top-levelness of those functions, instead of this convention forcing that as a side-effect.

**Comment by tfausak** [comment]
As I said, I only slightly prefer multiple `let`s. I like how they make it easy to add or remove lines of code without having to change where the `let` is. On the other hand, using a single `let` matches `let ... in ...` a lot more closely. 

Since my preference isn't that strong and I'm outnumbered, let's go with single `let`s. We'll make a separate guideline to dissuade mutually recursive declarations.

**Comment by tfausak** [comment]
Oh, I just remembered something I don't like about single `let`s: The declarations in a `let` aren't ordered, so you can use a value before it's defined. For example:

``` hs
let
  x = y
  y = 1
in x
```

Unfortunately for pure code, the only way to systematically avoid this is to only allow a single definition in each `let`, like how Dhall does things. I am not a fan of that style though.

``` hs
let y = 1
in let x = y
in x
```

I still think using a single `let` is the best guideline, along with separate guidelines for avoiding mutually recursive declarations and avoiding out-of-order declarations.

**Comment by tfausak** [comment]
I think these days we prefer single `let`s where possible.

**Comment by aschmois** [comment]
Yeah. Sometimes it can get confusing when refactoring but in general makes the code cleaner.
