### ISSUE TITLE
Avoid mixing ADTs and records

### ISSUE THREAD

**Issue by tfausak** [EdutainmentLIVE/haskell-style-guide#27]
``` hs
-- bad
data T = C1 { f1 :: Int } | C2 { f2 :: Double }

-- good
data T = C1 T1 | C2 T2
newtype T1 = T1 Int
newtype T2 = T2 Double
```

In general, a data type should either be an ADT (`data T a b = C1 a | C2 b | ...`) or a record (`data T a b = C { f1 :: a, f2 :: b, ... }`). Mixing both is a recipe for disaster. In the above example, `f1` has type `T -> Int`, but it's partial and will explode at runtime when passed `C2 3.4`.

**Comment by telser** [comment]
Perhaps another example could be that the combination the other way is okay? Such as
`data T = S { f1 :: Int, f2 :: H }`
`data H = C1 | C2 | C3`

**Comment by qxjit** [comment]
Absolutely. This is one that I actually would vote for making a compiler error, if that option were available.

**Comment by tfausak** [comment]
GHC 8.4 introduced `-Wpartial-fields` that does exactly this!
https://ghc.haskell.org/trac/ghc/ticket/7169
https://phabricator.haskell.org/D4083

```
$ stack --resolver ghc-8.4.3 exec -- ghci -Wpartial-fields
> data T = C1 | C2 { f :: () }
<interactive>:1:20: warning: [-Wpartial-fields]
    Use of partial record field selector: `f'
```

It's not included in `-Wall`, but it is included in `-Weverything`.

**Comment by tfausak** [comment]
Unfortunately even GHC 8.6.3 with `-Weverything` doesn't complain about the _same_ field being used across multiple constructors of the same type. That makes sense, but it means there isn't a way to enforce this suggestion with compiler warnings.

``` hs
>>> data T2 = T2C1 { t2f1 :: () } | T2C2 { t2f1 :: () }
>>>
```

**Comment by telser** [comment]
That is true and very :(. I've seen ghc will complain about usages of those with `-Wpartial-fields`, but it could have been the same field used on _some_ of the constructors instead of _all_. Removing this stuff from the codebase I'm thinking of is still a to-do.
