### ISSUE TITLE
Avoid re-exports and new declarations in the same module

### ISSUE THREAD

**Issue by tfausak** [EdutainmentLIVE/haskell-style-guide#28]
``` hs
-- bad
module M ( module N, f ) where
import N
f = undefined

-- good
module M.F ( f ) where
f = undefined

module M ( module N, f ) where
import N
import M.F
```

If a module more or less re-exports other modules, that's all it should do. New declarations should go into other modules that will then get pulled into the re-exporter.

**Comment by tfausak** [comment]
One other thing related to this is that modules "inside" a hierarchy shouldn't import modules above them in the hierarchy that only re-export stuff. For example, if you have `M.N.A` and `M.N`, then `M.N.A` probably shouldn't be reaching "up" and importing `M.N`.

**Comment by telser** [comment]
I agree completely. Though IIRC I've seen a codebase or two with a mixture recently. Not sure if any of the other Flipstone people could comment with a good reason for them though. Maybe avoiding unnecessarily wide or deep hierarchies, but I'm not sure I'd buy that argument.

**Comment by qxjit** [comment]
I totally agree. Places where they are currently mixed are either simply a result of not fully embracing this style, or incomplete transitions of breaking out submodules.
