### ISSUE TITLE
Avoid unnecessary type wrappers

### ISSUE THREAD

**Issue by tfausak** [EdutainmentLIVE/haskell-style-guide#39]
This is kind of the opposite of #38. We sometimes use this pattern to return JSON from handlers:

``` hs
newtype Response = Response X

instance ToJSON Response where toJSON (Response x) = something x

handler = do
  ...
  pure . json $ Response x
```

This is a lot of overhead to return some JSON. And we're not getting any more safety from the type wrapper because we're constructing it and then immediately converting it to JSON. So instead of all that, I think it's better to provide an `xToJSON` function and call it:

``` hs
xToJSON :: X -> Value
xToJSON x = something x

handler = do
  ...
  pure . json $ xToJSON x
```

If `xToJSON` is simple enough, it might make sense to inline it. Otherwise I like keeping it as a separate top-level declaration for clarity.

**Comment by gera-cameron** [comment]
I'm down with this! ❤️

**Comment by tfausak** [comment]
Now that we're using more Servant and Swagger, we actually get some use out of these extra types. I'm going to close this.
