### ISSUE TITLE
Avoid big tuples

### ISSUE THREAD

**Issue by tfausak** [EdutainmentLIVE/haskell-style-guide#40]
Maybe use a "real" data structure (aka a record) once you get to a 3- or 4-tuple.

**Comment by gera-cameron** [comment]
I like big tuples and I can not lie.

**Comment by gera-cameron** [comment]
I would agree unless you need it for a case statement.

**Comment by aschmois** [comment]
> I would agree unless you need it for a case statement.

I think this could become an antipattern on bigger tuples. Hard to say without concrete examples but you can usually represent an nTuple as an ADT or possibly a list.
