### ISSUE TITLE
Prefer foldMapWithKey to uniformly transform map keys/values

### ISSUE THREAD

**Issue by codygman** [EdutainmentLIVE/haskell-style-guide#42]
A side-effect of doing bulk queries upfront and then using maps to do lookups later is frequently needing to change those map keys and values uniformly. Initially we thought it wasn't easily possible, but after some investigation found the solution enclosed.

Simplest example:

```
λ> Map.foldMapWithKey (\key val -> Map.singleton (key + 1) (val + 1)) (Map.singleton 1 1)
fromList [(2,2)]
```

Real world example (our use case):

```
transformMap
  :: Map.Map UserId User
  -> UserId
  -> SavedAssignment
  -> Map.Map Username AssignmentExternalId
transformMap userMap userId_ assignment_ = case (Map.lookup userId_ userMap) of
  Just user_ ->
    Map.singleton (userName user_) (savedAssignmentExternalId assignment_)
  Nothing -> Map.empty

usingFoldMapWithKey
  :: Map.Map UserId User
  -> Map.Map UserId SavedAssignment
  -> Map.Map Username AssignmentExternalId
usingFoldMapWithKey userMap uIdAsgmtMap =
  Map.foldMapWithKey (transformMap userMap) uIdAsgmtMap
```

You should probably lean towards making your function you `foldMapWithKey` a top-level function with a descriptive name unless the transformation is trivial and doesn't create line noise.

**Comment by tfausak** [comment]
I typically tackle problems like this by converting the map into a list, doing the transformation, and then converting the list back into a map. I've never actually used `foldMapWithKey`, but maybe I should!

**Comment by tfausak** [comment]
I don't think this comes up often enough to warrant a style guide entry. I feel like normally we modify the keys or the values but not both.

**Comment by tfausak** [comment]
I don't think I like that. Consistently using the same function (`foldMapWithKey`) means you can't tell at a glance what the expression with doing. With `Map.map` (or `fmap`), I know the keys are staying the same and we're changing the values one at a time. 

I think you could make an equivalent argument for always using `foldr` instead of `fmap`, `filter`, `concatMap`, and so on.

**Comment by codygman** [comment]
I agree with you, but something interesting is that I think we are giving up explicitness in some dimension, perhaps just the familiarity dimension.

I think it's fine to say we prefer the less powerful and more structured Loops (but more implicit) constructs that you're expected to learn beforehand over the more familiar and more powerful foldr. 

In fact, I prefer less powerful constructs with more guarantees that usually require more upfront learning in general.

Also, I really really don't like that example I proposed.. lol

I do however like the resulting thoughts and discussion 😃
