### ISSUE TITLE
Prefer test for each function or reduce duplication and only keep higher level tests

### ISSUE THREAD

**Issue by codygman** [EdutainmentLIVE/haskell-style-guide#45]
Should we prefer a test for each function or are tests that effectively test those functions enough?

In this specific case, we saw it more as duplication since it's already tested:

https://github.com/EdutainmentLIVE/smurf/commit/2decea0d9d634a834f35fcf73e7e6616f0dbdd96

Is this the pattern we want to follow? Seemed like a good example of this question in action to start a discussion.

**Comment by tfausak** [comment]
I'm not sure if this is something that can be answered in a style guide. Do we want to write tests for each function, even if that means duplicating some of the checks? Or do we want to aim for "merely" 100% test coverage, regardless of how many top-level functions we end up testing?

**Comment by tfausak** [comment]
I'm still not sure this belongs in the style guide. Also I don't think we've reached consensus yet, so I'm going to close this for now.
