### ISSUE TITLE
Avoid applicative style in typeclass instances

### ISSUE THREAD

**Issue by codygman** [EdutainmentLIVE/haskell-style-guide#48]
No doubt related to #29.

We had things in the wrong order with:

```haskell
instance Aeson.FromJSON EpisodeAugmentation where
  parseJSON = Aeson.withObject "EpisodeAugmentation" $ \o ->
    EpisodeAugmentation
      <$> Json.requiredJSONKey o "episodeTitle"
      <*> Json.requiredJSONKey o "courseName"
      <*> Json.requiredJSONKey o "episodeLength"
```

We should consider doing:

```haskell
epAugTitle <- Json.requiredJSONKey o "episodeTitle"
epAugLen <- Json.requiredJSONKey o "episodeLength"
epAugCourse <- Json.requiredJSONKey o "courseName"
EpisodeAugmentation
  { episodeAugmentationTitle = epAugTitle
  , episodeAugmentationLength  = epAugLen
  , episodeAugmentationCourse  = epAugCourse
  }
```

Or we can add tests like was done to prevent this issue. The second style is more verbose but it prevents that issue from happening.

**Comment by tfausak** [comment]
There is another way to avoid this problem, but it introduces a lot of boilerplate. You can make helper functions for getting each of the fields and then call those. For example:

``` hs
getEpisodeTitle :: Aeson.Object -> Aeson.Parser EpisodeTitle
getEpisodeTitle o = Json.requiredJSONKey o "episodeTitle"
```

Also that only really works if each field has a unique type, otherwise it's still possible to mix them up. 

I like the idea of using `do` notation. I think I mentioned this in #29, but I also like the idea of using `NamedFieldPuns` to get rid of some of the duplication. 

``` hs
instance Aeson.FromJSON EpisodeAugmentation where
  parseJSON = Aeson.withObject "EpisodeAugmentation" $ \ object -> do
    episodeAugmentationTitle <- Json.requiredJSONKey o "episodeTitle"
    episodeAugmentationLength <- Json.requiredJSONKey o "episodeLength"
    episodeAugmentationCourse <- Json.requiredJSONKey o "courseName"
    pure EpisodeAugmentation
      { episodeAugmentationTitle
      , episodeAugmentationLength
      , episodeAugmentationCourse
      }
```

`RecordWildCards` would get rid of even more duplication, but I'm not comfortable with that extension in general. This comment summarizes my feelings well: https://np.reddit.com/r/haskell/comments/6jaa5f/recordwildcards_and_binary_parsing/djd5ugj/

**Comment by tfausak** [comment]
There is one other way around this problem that avoids boilerplate in the instance definition: Defining a bunch of helper functions. I think we use this in our codebase to get environment variables, for example.

``` hs
-- bad

instance FromJSON User where
  parseJSON = withObject "User" $ \ object -> User
    <$> object .: "age"
    <*> object .: "name"
    
-- good, verbose

instance FromJSON User where
  parseJSON = withObject "User" $ \ object -> do
    age <- object .: "age"
    name <- object .: "name"
    pure User
      { userAge = age
      , userName = name
      }

-- good, slightly less verbose

{-# LANGUAGE NamedFieldPuns #-}
instance FromJSON User where
  parseJSON = withObject "User" $ \ object -> do
    userAge <- object .: "age"
    userName <- object .: "name"
    pure User { userAge, userName }

-- okay, lots of functions

instance FromJSON User where
  parseJSON = withObject "User" $ \ object -> User
    <$> getUserAge object
    <*> getUserName object

getUserAge :: Object -> Parser Age
getUserAge object = object .: "age"

getUserName :: Object -> Parser Name
getUserName object = object .: "name"
```

The additional verbosity probably isn't worth it. Also this only truly solves the problem if each record field has a unique type, which isn't always the case. 

My personal favorite is `do` notation with `NamedFieldPuns`.
