### ISSUE TITLE
Using Deprecated pragmas

### ISSUE THREAD

**Issue by aschmois** [EdutainmentLIVE/haskell-style-guide#52]
https://downloads.haskell.org/~ghc/7.0.3/docs/html/users_guide/pragmas.html

I think we should start using deprecation in our codebase on stuff we want to cleanup but don't want to do so in a big PR.

This helps in keeping some list that we can output somewhere of what's left to cleanup.

Downsides:
- Semaphore would need to ignore deprecation warnings as it builds with pedantic
- Would probably have to ignore in ghcid as well since tests don't get run if you have warnings. Ignoring in ghcid would defeat the purpose of having it.

I think to solve the second downside we can generate deprecation warnings report that way we can see it somewhere in our pipeling if we want to but would otherwise be completely ignored.

The way I've seen it done in things like Java is that a report is generated by your CI and it displays it somewhere. It can be github, it can be an email, or w.e.

**Comment by tfausak** [comment]
I wish there was a way to mark something as deprecated moving forward. Current usages are alright, anything new isn't. 

I would settle for line or block oriented pragmas to disable deprecations, like we have for HLint, but as far as I know that isn't possible either. 

As it is I don't think deprecations through GHC are ergonomic enough. Maybe we can disallow functions from HLint and enforce things that way?

**Comment by aschmois** [comment]
I haven't forgotten about this issue, I'd like to come up with some solution.

**Comment by tfausak** [comment]
I'm not sure what I was thinking before; HLint should be able to do this. You can mark a function as verboten in your HLint config, then you can use inline pragmas to allow it at certain call sites.

**Comment by aschmois** [comment]
Ooo wee, it's time.

**Comment by tfausak** [comment]
Closing this since I think it's more of a process issue than a style guide thing.
