### ISSUE TITLE
Avoid Path Parameters

### ISSUE THREAD

**Issue by aschmois** [EdutainmentLIVE/haskell-style-guide#53]
Path parameters don't really add a lot. They also make reading logs and metrics a lot harder to group endpoints. Another upshot is that the parameters are named and not positional.

When writing a new endpoint:

Bad:

`api/urza/v3/cool-service/user/{user-external-id}/info`

Good:

`api/urza/v3/cool-service/user/info?userExternalId={user-external-id}`

**Comment by tfausak** [comment]
I don't mind path parameters with known formats, like UUIDs. They're especially useful when things are nested:

- `/api/company/:company-id/user/:user-id`
- `/api/company-user?company=:company-id&user=:user-id`

That being said I'd definitely prefer to avoid path parameters for things that are an unknown format, like episode slugs or search queries.

**Comment by aschmois** [comment]
That's only true for our custom metrics, logs still show the path. Should we be logging differently too? Maybe we can log with the custom way but also log the path parameters separately. Though I think I would still preferr to just query parameter everything for consistency.

**Comment by tfausak** [comment]
Ah, I see what you're saying. I could get on board with that. Maybe we can print out all our API endpoints and see what converting them all to use query parameters would look like?

**Comment by tfausak** [comment]
Closing this since it relates to HTTP API design rather than Haskell style.
